apiVersion: v1
kind: Service
metadata:
  name: dero-cluster
  namespace: clusterchess-backend
spec:
  selector:
    app: clusterchess-backend
  ports:
    - port: 4369
      targetPort: 4369
      name: epmd
    - port: 80
      targetPort: 80
      name: http
  clusterIP: None
  type: ClusterIP