apiVersion: v1
kind: Service
metadata:
  name: clusterchess-backend-sv
  namespace: clusterchess-backend
spec:
  selector:
    app: clusterchess-backend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
