apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: clusterchess-backend-session
  namespace: clusterchess-backend
spec:
  plugin:
    stickyCookie:
      name: clusterchess-backend-session
      secure: true
      httpOnly: true
      sameSite: lax